Vagrant.configure("2") do |config|
  config.vm.define "zabbix1", primary:true do |web|
    web.vm.box = "sbeliakou/centos-6.7-x86_64"
    web.vm.hostname = "zabbix1"
    web.vm.network "private_network", ip: "192.168.100.91"
    web.vm.provider "virtualbox" do |host|
	host.name="zabbix1"
	host.cpus = 1
	host.memory = 2048 
	end
    web.vm.provision "shell", inline: <<-SHELL
echo "Host is ready!!"
SHELL
  end
#  config.vm.define "pnode1", primary: true do |web|
#    web.vm.box = "centos/7"
#    web.vm.hostname = "node1"
#    web.vm.network "private_network", ip: "192.168.100.121"
#    web.vm.provider "virtualbox" do |host|
#        host.name="node1"
#        host.cpus = 1
#        host.memory = 1024
#        end
#    web.vm.provision "shell", inline: <<-SHELL
#ehco "Host is ready!!"
#SHELL
#  end

  config.vm.provision "shell", inline: <<-SHELL
   echo "Provisioning hosts is ready for provisioning"
   rpm -ivh http://repo.zabbix.com/zabbix/2.2/rhel/6/x86_64/zabbix-release-2.2-1.el6.noarch.rpm
   yum -y install zabbix-agent
   SHELL
end
